import React from 'react'

const Company = () => {
  return (
    <div><div className='md:h-fill-purple-100 no-scrollbar md:h-auto  md:w-auto h-screen w-full overflow-y-auto md:overflow-hidden bg-white  p-4'>
    <h1 className='w-full py-8 text-center font-Syne text-lg font-bold text-text-primary  md:text-3xl lg:text-[3.2rem] '>Companies that Hire from us</h1>
  <div className="grid gap-10 w-screen grid-cols-2 place-items-center md:grid-cols-4 p-4 lg:grid-cols-6 bg-white">
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/Flix.ae4e3dc7.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/ACT_Fibernet.4e104666.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/Ajanta.c14f5889.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/Altrust.9a065144.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/Amazon.b926fcec.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/Au.d61eeb99.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="	https://joboxhire.com/_next/static/media/axis-bank.b27e7078.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/BharatPe.457b56a0.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/Bigbasket.5bd17d84.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/Blinkit.6336f9d4.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="	https://joboxhire.com/_next/static/media/Bounce-Logo.6592ec4f.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/Byjus.04dba0cf.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="	https://joboxhire.com/_next/static/media/crm.5fcd68f7.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="	https://joboxhire.com/_next/static/media/DairyDay.d036202f.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/Delivery.com.9e23b158.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/equitas.7b354071.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/Hathway.71297858.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/Homefirst.466412fd.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="	https://joboxhire.com/_next/static/media/Hrhnext.039e4f5a.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/Hypersupermarket%20.44a46226.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="	https://joboxhire.com/_next/static/media/IDFC.b3556ecc.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/InnovativePayments.450d567e.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="	https://joboxhire.com/_next/static/media/Instamart.b74e9d70.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/JanaSmallFinanceBank.6b0151b9.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="	https://joboxhire.com/_next/static/media/JapanGrabTechnologies.96ecd73e.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="	https://joboxhire.com/_next/static/media/Katerra_Primary_Logo.22c20d88.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="	https://joboxhire.com/_next/static/media/KbxDigital.4f82c570.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/LandT.5c4e40cb.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/oppo-mobile-logo.fb3714a7.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/Qconnect.5ecfac0a.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/Sigmaoilseeds.4237ee8b.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="	https://joboxhire.com/_next/static/media/sigma.62efa399.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/Tatamotors.4db2020c.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="https://joboxhire.com/_next/static/media/teleperformance.06002c2f.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="	https://joboxhire.com/_next/static/media/Toppr.784fddd0.svg"/></div>
    <div className="flex items-center justify-center rounded-md shadow-lg bg-white transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white-500 duration-300"><img alt="Companies" draggable="false" loading="lazy" width="133" height="43" decoding="async" data-nimg="1" className=" aspect-[4/3] h-[4rem] w-[12rem] object-contain px-1 py-2 mix-blend-multiply" src="	https://joboxhire.com/_next/static/media/Zepto.630c9f92.svg"/></div>
  </div>
  </div></div>
  )
}

export default Company